viamrobotics/viam-python-sdk

src/viam/services/vision.py
tests/test_vision_service.py

the parameter list was left over from the old segmenter method. This is updated and fixed.

Edit GetObjectPointClouds Segmenter method

---

README.md

Hi folks 👋! While reading I noticed some broken links. Also added some other improvements that make this easier to read. Of course, edit these as you see fit 😊

Small rewrites for clarification

---

.github/workflows/docs.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml
.gitignore
Makefile
README.md
docs/examples/example.ipynb
etc/postinstall.sh
examples/echo/v1/client.py
pyproject.toml
src/viam/__init__.py
src/viam/components/movement_sensor/movement_sensor.py
src/viam/robot/client.py
src/viam/rpc/dial.py
tests/test_robot.py

Add the rust library, and release!
* Add a new `dial` function that calls out to rust
* Deprecate old `dial_direct` function (still available)
* Update the release workflow to
* Grab the most recent compiled rust and include it in the package
* Create a GitHub draft release and tag
* Create a publish workflow to push binaries to PyPI on release published
* Update README to include new installation instructions

Rust and Release

---

src/viam/robot/client.py
src/viam/rpc/dial.py
src/viam/utils.py
tests/test_utils.py

Only allowed to initialize the rust runtime once, and thus only release it once.

One Runtime to Rule them All

---

src/viam/rpc/dial.py
src/viam/utils.py

And also add a lock to retrieving `PointerCounter.count`

Add debug logging around viam-rust-utils

---

examples/server/v1/components.py
pyproject.toml
src/viam/media/media.py
src/viam/registry.py
src/viam/robot/service.py
src/viam/rpc/server.py
src/viam/utils.py
tests/mocks/components.py
tests/test_registry.py

Decrease minimum python version to 3.8, which is the default for ubuntu

Decrease minimum python version

---

src/viam/components/sensor/client.py
src/viam/components/sensor/sensor.py
src/viam/components/sensor/service.py
tests/mocks/components.py
tests/test_sensor.py

JIRA: https://viam.atlassian.net/browse/RSDK-810

RSDK-810 Add extra params to sensor

---

src/viam/components/movement_sensor/client.py
src/viam/components/movement_sensor/movement_sensor.py
src/viam/components/movement_sensor/service.py
tests/mocks/components.py
tests/test_movement_sensor.py

JIRA: https://viam.atlassian.net/browse/RSDK-808

RSDK-808 Add extra params to movementsensor

---

src/viam/components/pose_tracker/client.py
src/viam/components/pose_tracker/pose_tracker.py
src/viam/components/pose_tracker/service.py
src/viam/components/servo/client.py
src/viam/components/servo/service.py
src/viam/components/servo/servo.py
tests/mocks/components.py
tests/test_pose_tracker.py
tests/test_servo.py

Extra params for PoseTracker and Servo

Extra params

---

.github/workflows/test.yml
doc/dependency_decisions.yml
poetry.lock
pyproject.toml

This PR updates all our dependencies and makes us compatible with python 3.11

Add support for python 3.11

---

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

was gonna try restricting to our team only, but kinda annoying to do.
can use https://github.com/garnertb/get-team-members, but then have to to install `gh` and `jq` onto the image, and I haven't found an image with both preinstalled

allow viamrobotics members to release

---

src/viam/logging.py

sends errors to stderr and regular logs to stdout.
follows how we do it in the rdk

RSDK-872: Log to stdout, errors to stderr

---

src/viam/services/motion.py

some updates around those docs.
also update get_pose so that we don't pass in [] for the optional parameter (just for safety reasons)

RSDK-670: update docs around creating resource names

---

examples/apis.json

Need to update the movementsensor default function to be compatible with all current movementsensor models

APP-1323- Update movementsensor function

---

src/viam/components/arm/service.py
src/viam/components/audio_input/service.py
src/viam/components/base/service.py
src/viam/components/board/service.py
src/viam/components/camera/service.py
src/viam/components/gantry/service.py
src/viam/components/gripper/service.py
src/viam/components/input/service.py
src/viam/components/motor/service.py
src/viam/components/movement_sensor/service.py
src/viam/components/pose_tracker/service.py
src/viam/components/sensor/service.py
src/viam/components/servo/service.py
tests/mocks/services.py
tests/test_movement_sensor.py

should've checked before merging - `make test` succeeds with these changes

fixes for automated protos update

---

Makefile

Exclude more file types from linting

Add newly generated files to exclude

---

src/viam/components/input/client.py

some errors were getting swallowed without this reraise

reraise trigger event error

---

docs/examples/example.ipynb

Not confident in my formatting, nor that this is the best way to word this.

Update example.ipynb to clarify custom implementation requirements

---

src/viam/components/generic/__init__.py

we were no longer import the service description because we were no longer importing the generic_pb2 file :/

Add Generic service descriptor import

---

docs/index.md

for some of the new folders we added

Generate some more docs

---

src/viam/rpc/dial.py

not sure if we should be a bit more strict on this check, but this is a quick pass on letting users connect to app.viam robots on the same host

RSDK-2203 - Update server hostname if address and auth_entity don't match

---

src/viam/robot/client.py

While trying to debug a user's issues, I figured we could make some improvements to our reconnection code.
Now we attempt to check connection if either `check_connection_interval` or `attempt_reconnect_interval` are greater than 0
We also have improved error messaging.

Minor improvements to reconnection

---

src/viam/logging.py
src/viam/rpc/server.py

re-up of https://github.com/viamrobotics/viam-python-sdk/pull/247

Fix log level setting

---

Makefile
examples/module/run.sh
poetry.lock
src/viam/components/movement_sensor/movement_sensor.py
src/viam/module/module.py

termination signals were not getting forwarded to the python module from the shell script that started the process. simple fix: just `exec` the python module from inside the shell script

[RSDK-2412] odrive module fix

---

src/viam/components/movement_sensor/movement_sensor.py

Proto changes have already been pulled into main.

RSDK-2806: Update movement sensor documentation for units

---

src/viam/services/motion/__init__.py
src/viam/services/sensors/__init__.py
src/viam/services/vision/__init__.py
tests/test_motion_service.py
tests/test_sensors_service.py
tests/test_vision_service.py

This reverts commit f3544dc230b676d633594d3d66ffc0745bd4257b. we're going to rollforward with the breaking change

Revert "add alias to service clients (#279)"

---

.github/workflows/publish.yml
.github/workflows/release-candidate.yml
.github/workflows/release.yml

Have to merge this into main before I can test it on it's own branch (bleh)

New release-candidate workflow

---

src/viam/components/arm/client.py
src/viam/components/arm/service.py
src/viam/components/gantry/client.py
src/viam/components/gripper/client.py
src/viam/components/motor/client.py
src/viam/components/servo/client.py
src/viam/resource/rpc_service_base.py
src/viam/robot/service.py

Finishing up what @purplenicole730 started with `Base` :)

Remove extra params from is_moving

---

src/viam/components/encoder/encoder.py
src/viam/services/vision/vision.py

RSDK-2936, RSDK-4175 - Update encoder get_properties, add count to get_classifications

---

src/viam/resource/types.py

unnormalize api/model name

---

examples/apis.json

due to go issue with Voltage returning 3 values: https://github.com/viamrobotics/rdk/pull/2810

RSDK-4649 Update code sample to use get_power

---

docs/examples/example.ipynb
src/viam/app/data_client.py
src/viam/services/motion/__init__.py
src/viam/utils.py

This code makes a few "cosmetic" changes to some of the classes housed within the 'app' directory and some of our documentation. Namely, the examples notebook is updated to make the output of a code cell more readable. A few docstrings within the clients are updated/corrected/reworded. An assertion error is swapped out for a value error. The last changes are an update to the tabular data methodology mechanism and the elimination of some redundant conditional logic in the filter helper method.

[RSDK 4604] Refine Examples & Refactor Code

---

src/viam/utils.py

Bug fix from https://github.com/viamrobotics/viam-python-sdk/pull/416

DATA-1813 Fix KeyError when fromDataManagement is not in extra

---

src/viam/utils.py

sorry about being confusing, the part I removed is no longer needed if you took my suggestion

Remove unnecessary check

---

src/viam/app/data_client.py
tests/mocks/services.py
tests/test_data_sync_client.py

RSDK-4978 - return file id from upload

---

docs/conf.py
poetry.lock
pyproject.toml

astroid apparently released a new major version recently

RSDK-5409 - Fix docs generation

---

.github/workflows/test.yml

https://github.com/viamrobotics/viam-python-sdk/pull/475#issue-1971131786

RSDK-5577 - Run tests on PR to RCs

---

src/viam/app/app_client.py

@stuqdog can we lint for docsstring correctness?

Fix formatting for docs

---

src/viam/services/motion/client.py
tests/mocks/services.py

https://viam.atlassian.net/browse/RSDK-6609

RSDK-6609 - Change implementation of MoveOnMap to include obstacles

---

src/viam/components/component_base.py
src/viam/components/encoder/encoder.py
src/viam/components/gantry/gantry.py
src/viam/resource/base.py

Python methods are copied from docs.viam.com and should therefore be correct. You do not need to test each method but feel free to scan over them. It is possible there are mistakes.

DOCS-1871: Update camera, encoder, gantry examples

---

src/viam/components/arm/arm.py
src/viam/components/base/base.py
src/viam/components/board/board.py
src/viam/components/camera/camera.py
src/viam/components/encoder/encoder.py
src/viam/components/gantry/gantry.py
src/viam/components/generic/generic.py
src/viam/components/gripper/gripper.py
src/viam/components/input/input.py
src/viam/components/motor/motor.py
src/viam/components/movement_sensor/movement_sensor.py
src/viam/components/power_sensor/power_sensor.py
src/viam/components/sensor/sensor.py
src/viam/components/servo/servo.py

I hadn't added the imports for the other components but think it's a good idea, so adding them here. Let me know what you think.

DOCS-1873: Add remaining component methods and imports

---

src/viam/robot/client.py

follow-up to https://github.com/viamrobotics/viam-python-sdk/pull/545

RSDK-6664 correct docs

---

examples/apis.json

Add extra comment to the vision service code snippet about changing it to get_detection if necessary
@npentrel @mestcihazal

RSDK-6487, RSDK-4456 : Update comment for vision service code snippet

---

src/viam/logging.py

Tested with @thegreatco and confirmed that this fix works.

RSDK-7195: fix no event loop logging error

---

src/viam/services/vision/__init__.py
src/viam/services/vision/client.py
src/viam/services/vision/service.py
src/viam/services/vision/vision.py
tests/mocks/services.py
tests/test_vision_service.py

Adds two new methods, and tests for them
- GetProperties
- CaptureAllFromCamera
Adding it to the rc-0.21.0 branch

RSDK-7565, RSDK-7471: add new methods get_properties and capture_all_from_camera

---

examples/apis.json

Changes the code sample for the front-end to use the new "get_properties"

Simplify the vision service code sample

---

pyproject.toml
src/viam/media/utils/pil/__init__.py
src/viam/media/utils/pil/viam_rgba_plugin.py
src/viam/media/viam_rgba.py
src/viam/media/video.py

There was one last spot where we were importing from a file that imported from PIL. Gotta remove that. Tested on a fresh installation.

Migrate remaining PIL features away

---

src/viam/app/app_client.py

Adds missing return data type and desc.
- This looks good in `make install && make documentation`

Fix missing return

---

src/viam/app/app_client.py

Add missing data type `bool` to param `send_email_invite` for method `create_organization_invite()`.

Fix missing data type

---

README.md
etc/generate_proto_import.py
src/viam/app/app_client.py
src/viam/app/data_client.py
src/viam/gen/service/mlmodel/v1/mlmodel_pb2.pyi
src/viam/module/module.py
src/viam/operations.py
src/viam/resource/registry.py
src/viam/resource/types.py
src/viam/services/mlmodel/__init__.py
src/viam/services/mlmodel/utils.py
src/viam/utils.py

I think that's the last of the latin abbreviations - thanks for letting us change these.

Remove latin abbreviations

---

examples/apis.json

In support of making it easier for fleet to have accurate code samples

Add new fields to apis.json

---

src/viam/services/vision/vision.py

Fix `get_properties` code sample. Renders in local staging.

Fix get_properties code sample

---

tests/test_ml_training_client.py

Was removed as part of this PR: https://github.com/viamrobotics/api/pull/521

Fix ml training test

---

.github/workflows/license_finder.yml
src/viam/robot/client.py

not quite sure how to fix the errors

Update get_status signature

---

src/viam/robot/client.py
tests/test_robot.py

https://viam.atlassian.net/browse/RSDK-8383

[RSDK-8383] Add robot get_version

---

examples/simple_module/README.md

Update simple module config in its README.md

---

src/viam/logging.py
src/viam/module/module.py

This is an alternate attempt at https://github.com/viamrobotics/viam-python-sdk/pull/730
Opening PR so that it's easier to share

[RSDK-8684] Try with futures

---

src/viam/app/app_client.py

* mirrors docs pr for DOCS-2901 
* updates from QA testing

DOCS-2901: Fleet management api code QA 

---

src/viam/components/arm/arm.py
src/viam/components/base/base.py
src/viam/components/camera/camera.py
src/viam/resource/base.py

Fix arm, base, camera snippets

---

src/viam/components/servo/servo.py
src/viam/resource/base.py

DOCS-2951: Make edits from QA to component api code samples

---

src/viam/components/gantry/gantry.py
src/viam/components/input/input.py

* make fixups to code samples
* checked gantry-input controller

DOCS-2950: Make fixups from QA to gantry, input controller

---

src/viam/services/mlmodel/client.py
src/viam/services/mlmodel/mlmodel.py
src/viam/services/mlmodel/service.py
tests/mocks/services.py

Needed for a project (see https://github.com/viamrobotics/app/pull/6753)

Add extra params to MLModel

---

.github/workflows/docs.yml
.github/workflows/linkcheck.yml

Tested to make sure nothing broke by running `Generate docs` on my branch using these changes https://github.com/viamrobotics/viam-python-sdk/pull/804/commits/3a55372f1330581b002a95c815cdc210f54c1c54.
Wasn't sure how to test `linkcheck` workflow, but I don't think it should affect anything, especially since we're not uploading multiple artifacts with the same name.

RSDK-9518: upgrade upload artifact to v4

---

src/viam/app/data_client.py

see https://viaminc.slack.com/archives/C0653ULNNAX/p1739186248273129

flyby - fix param reference

---

src/viam/app/data_client.py

Fix typo in data client

---

.github/workflows/update_protos.yml
Makefile
pyproject.toml

Context:
https://viaminc.slack.com/archives/C0653ULNNAX/p1739929333482249

RSDK-10026 Update protobuf to 5.29.2

---

src/viam/module/module.py

Add module logs that are named.
See screenshot below of custom added log message. This was added to the `add_resource` method in a`module.py`. Note how it indicates that it comes from `my-module` rather than `viam.module.module`.

RSDK-9921 - named module logger

---

examples/apis.json
src/viam/components/button/__init__.py
src/viam/components/button/button.py
src/viam/components/button/client.py
src/viam/components/button/service.py
tests/mocks/components.py
tests/test_button.py

This code was generated using Claude following the pattern of #862

RSDK-10279: Button component

---

.github/workflows/build-wheels.yml

got whl and arch mixed up :facepalm:

fix windows platform tag, take 2

---

src/viam/app/data_client.py
src/viam/utils.py

This PR fixes the GetLatestTabular data. If not specifying additional params, we should set them to none.

DATA-fix get latest

---

src/viam/app/app_client.py
tests/mocks/services.py
tests/test_app_client.py

RSDK-11648- add version param for get_fragment

---

src/viam/app/data_client.py
tests/test_data_pipelines.py

Hey yall, this PR adds the error_message string to our SDK for users.

DATA-4502 Add error_message to python SDK
