- src/viam/robot/client.py
- tests/test_robot.py
just allows users to query for and cancel operations using the client. Tested with an actual rdk server
> RSDK-703 Add operation support to robot client

- docs/examples/example.ipynb
Update the example process ID to be a real string, not just an integer formatted as a string, to avoid confusion
> [RSDK-744] Update example process ID

- src/viam/components/arm/service.py
- src/viam/operations.py
- tests/test_operations.py
JIRA: https://viam.atlassian.net/browse/RSDK-594
Only implemented for arm service.
> RSDK-594 receive op id in python sdk

- Makefile
- poetry.lock
- pyproject.toml
- tox.ini
This allows us to test against all supported python versions locally with tox by running `make tox`
> Add multi-testing with tox

- src/viam/services/motion.py
This PR fixes a bug by updating the motion service's `get_pose` to pass `supplemental_transforms` in the GRPC request
> DATA-940 add supplemental_transforms to get_pose

- src/viam/components/audio_input/service.py
- src/viam/components/base/service.py
- src/viam/components/board/service.py
- src/viam/components/camera/service.py
- src/viam/components/gantry/service.py
- src/viam/components/generic/service.py
- src/viam/components/gripper/service.py
- src/viam/components/input/service.py
- src/viam/components/motor/service.py
- src/viam/components/movement_sensor/service.py
- src/viam/components/pose_tracker/service.py
- src/viam/components/sensor/service.py
- src/viam/components/servo/service.py
- tests/mocks/components.py
JIRA: https://viam.atlassian.net/browse/RSDK-594
Follow-up to: https://github.com/viamrobotics/viam-python-sdk/pull/188 - there we started passing metadata to the arm service methods to synchronize operation ids. This PR does that for all other component service methods.
> RSDK-594 Pass metadata into all service methods

- src/viam/rpc/dial.py
- src/viam/utils.py
using `asyncio.to_thread` was the only function that was not python 3.8 compatible. It turns out that this function is literally just some sugar that wraps the code I've added directly
https://github.com/python/cpython/blob/main/Lib/asyncio/threads.py
> proxy asyncio.to_thread

- src/viam/components/movement_sensor/movement_sensor.py
- tests/test_movement_sensor.py
[RSDK-2128](https://viam.atlassian.net/browse/RSDK-2128)
Currently, when a movement sensor does not have keys for all the possible readings, it returns an error. For example, the accelerometer on the Viam Rovers by default only have a linear acceleration reading set up. When a user calls `get_reading()` on the rover's accelerometer, an `GRPCError` is raised, failing out of the function altogether without any return.
The goal of this ticket is to be able to call `get_readings()` and return a dictionary that has default values for whatever reading is not supported on the sensor.
Calling `get_readings()` still returns an ERROR logs, but is able to return an incomplete library of `readings`.
```
2023-03-03 18:04:31,722         INFO    viam.rpc.dial (dial.py:212)     Connecting to socket: …
```
> RSDK 2128 allow partial movement sensor readings dictionary

- src/viam/__init__.py
- src/viam/module/module.py
- src/viam/resource/types.py
- tests/test_registry.py
Incorrectly had `ResourceName` being `namespace:type:subtype:name` rather than `namespace:type:subtype/name`. Whoops.
> Fix ResourceName delimiters

- examples/module/README.md
- examples/module/src/gizmo/__init__.py
- examples/module/src/gizmo/my_gizmo.py
- examples/module/src/summation/__init__.py
- src/viam/errors.py
- src/viam/module/module.py
- src/viam/module/service.py
- src/viam/resource/registry.py
- src/viam/resource/types.py
- tests/mocks/module/gizmo/__init__.py
- tests/mocks/module/gizmo/my_gizmo.py
- tests/mocks/module/summation/__init__.py
- tests/test_module.py
[RSDK-2071](https://viam.atlassian.net/browse/RSDK-2071)
Changes in this PR:
- Adds a new resource validator type with `lookup` and `register` functions to work with and store resource validators.
- Adds `validate_config` function that allows a module to look up and run (if any) a stored resource validator.
- Implements `ValidateConfig` to call `validate_config`.
- Adds a new gRPC error called ValidationError that will be raised when any Exception is thrown during `validate_config`.
- Test `validate_config` with example `Gizmo` module that stores a validator during init.
- Adds a validator function section to `README.md`
cc @benjirewis 
[RSDK-2071]: https://viam.atlassian.net/browse/RSDK-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rsdk 2071 support modular validation and implicit dependencies

- examples/module/src/main.py
not strictly necessary but if people are going to use this as an example, this might save some headache in the future
> RSDK-2797 - Allow more args to modules

- README.md
While going through [this tutorial](https://docs.viam.com/tutorials/get-started/make-an-led-blink-with-a-raspberry-pi-and-sdk/) users are directed to https://python.viam.dev/ 
I noticed that users are directed to download `this repository` but while in the docs site they are not already present in the repository, so it is confusing.
This PR adds a hyperlink to this `repository` sending users to the phython sdk repo https://github.com/viamrobotics/viam-python-sdk - which feels redundant in some cases, but in the case where that readme is read on https://python.viam.dev/  I think it makes sense to have the link for that case.
Testing Evidence:
> add link to python repo in readme

- docs/conf.py
a piece of feedback I got was that some of the inherited methods would be useful to see in the docs - however, doing it blindly will show documentation for far too much stuff, especially in the generated code
basically adds this section into every resource definition file
also fixed a typo in `show-inheritance`
> RSDK-2837 - Add some inherited methods to docs

- src/viam/rpc/dial.py
It seems like the previous SSL fix ([RSDK-2203 - Update server hostname if address and auth_entity don't match by cheukt · Pull Request #242 · viamrobotics/viam-python-sdk](https://github.com/viamrobotics/viam-python-sdk/pull/242) ) introduced a subtle bug where we now look for a connection to the auth_entity instead of localhost during the connection phase. I found this by monkeypatching socket.getaddrinfo and seeing that the args have changed.
I found this issue while at a friend's apartment -  not sure why this only doesn’t work in certain network configurations (the original code worked in the office and still works in my hotspot). Fix seems to be to pass `server_hostname` along as a different parameter
> RSDK-2844 - localhost connections fail in certain internet configurations

- Makefile
- src/viam/rpc/server.py
gRPC logs will now be debug for server requests
also:
[flyby] start generating all app protos. this will be run manually with the GitHub action
> [RSDK-2948] Set grpc request logs to debug

- src/viam/resource/manager.py
- tests/test_component_service_base.py
[RSDK-2930](https://viam.atlassian.net/browse/RSDK-2930)
When a resource is not registered completely, the server should return an error when starting up. Now, `Registry` checks to see if the component's subtype is registered.
As these changes were introduced, `TestComponent` also needed to be registered in the registry. 
[RSDK-2930]: https://viam.atlassian.net/browse/RSDK-2930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rsdk 2930 error when resource not registered

- src/viam/services/motion/__init__.py
- src/viam/services/sensors/__init__.py
- src/viam/services/vision/__init__.py
- tests/test_motion_service.py
- tests/test_sensors_service.py
- tests/test_vision_service.py
> add alias to service clients

- src/viam/rpc/dial.py
want to ignore this since this is unavoidable in some cases (with keyboard interrupts, for example) and should be generally safe
alternatively we can just not call close if event loop is already closed (which also requires catching a RuntimeError)
> Ignore Event Loop is closed error on close

- examples/module/src/main.py
- src/viam/module/module.py
- tests/mocks/components.py
- tests/test_base.py
(flyby) remove unused mock test in base
> Add new class method to create module from args

- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
make some changes so that running the release/rc workflow adds commits on top of the rc branch, not the main branch. 
I've seen `[[` fail in bash before in CI sometimes and not others, so updating the syntax to be a bit more resilient.
> workflow updates

- examples/module/src/gizmo/api.py
- examples/module/src/summation/api.py
- src/viam/components/arm/service.py
- src/viam/components/audio_input/service.py
- src/viam/components/base/service.py
- src/viam/components/board/service.py
- src/viam/components/camera/service.py
- src/viam/components/encoder/service.py
- src/viam/components/gantry/service.py
- src/viam/components/generic/service.py
- src/viam/components/gripper/service.py
- src/viam/components/input/service.py
- src/viam/components/motor/service.py
- src/viam/components/movement_sensor/service.py
- src/viam/components/pose_tracker/service.py
- src/viam/components/sensor/service.py
- src/viam/components/servo/service.py
- src/viam/resource/rpc_service_base.py
- src/viam/services/mlmodel/service.py
- src/viam/services/slam/service.py
- tests/mocks/module/gizmo/api.py
- tests/mocks/module/summation/api.py
Moved throwing of the `ResourceNotFoundError.grpc_error` to the superclass of all `<Resource>RPCService`s. This reduces a ton of boilerplate, especially around creating new services/module services
> Hoist error throwing to superclass

- src/viam/components/camera/service.py
- tests/mocks/components.py
- tests/test_camera.py
When the mime type is empty on a `camera.get_image` request, python was sending back an empty mime type instead of choosing a default mime type. 
I basically copied what's going on in RDK, which I saw @kharijarrett implemented, so tagging him as a reviewer.
Cc: @thegreatco this should help with oakd
> Select default mime type when empty

- README.md
Add a very small summary of what sessions are and how to disable them, as well as links to a higher level description of sessions in RDK.
> DOCS-835 Add minimal sessions summary + references to readme

- .github/workflows/publish.yml
When we publish a release, notify the python-sdk channel
> Add notification to publish workflow

- .github/workflows/release-candidate.yml
Fix an issue we realized after doing the hotfix with @maximpertsov that the PR opened is from the current branch, not the newly-created RC branch.
> HEAD in RC PR should be new RC branch

- .github/workflows/release-candidate.yml
GH CLI is only pre-installed on GH runners. Because we use custom runners, we're getting failures where our workflows use GH CLI.
> Install gh cli in workflow

- src/viam/rpc/server.py
This PR updates the Python SDK to include resource names in debug logs. It also causes debug logs to be generated twice for each endpoint - once when a message is received and once when a call is finished - for functions that have been implemented.
> [RSDK-3380] include resource names in debug logs

- src/viam/components/base/base.py
Related to this docs ticket https://viam.atlassian.net/browse/DOCS-845
> Clarify base coordinate system in comments

- src/viam/sessions_client.py
seems like having async tasks call themselves causes issues so refactored it a bit to resemble our other recurring tasks. (https://stackoverflow.com/questions/37512182/how-can-i-periodically-execute-a-function-with-asyncio)
behavior should be the same
> RSDK-3775 - Fix unawaited warning

- src/viam/app/client.py
- src/viam/app/data/client.py
- src/viam/rpc/dial.py
This PR includes a new (unimplemented) data client that uses location-level authentication to make requests to app. The methods included will allow for data to be uploaded to and retrieved from app programmatically.
> [RSDK-3628] Create Data Location Client Able to Connect to App

- etc/code-samples-action.py
The code samples refactor changed our file format for adding code samples. This broke a script that warns users about breaking code samples. This fix adjusts that script to correctly get the component and function names
> fix code sample warning

- src/viam/app/client.py
- src/viam/app/data/client.py
This PR implements and adds docstrings to the gRPC methods that'll allow a DataClient to send a gGRPC request to app to add, remove, and retrieve tags. The PR also implements a function to retrieve bounding box labels. There are a few other minor changes throughout. Namely, some function signatures are updated to include defaults for certain parameters (i.e. empty filter), and the AppClient "close()" function is implemented with logging.
> [RSDK-3634] Implement data.proto APIs that Add/Remove Tags

- examples/module/client.py
- src/viam/rpc/dial.py
Credential type is currently hard-coded as robot-location-secret, but we’re starting to also use robot-secret. We should update to make this a configurable value. We made this change first in cpp-sdk but also needs to be done in python-sdk.
> RSDK-3922 No hardcoding credential type in Python

- src/viam/components/camera/client.py
- src/viam/media/video.py
With the addition of `CameraMimeType.VIAM_RAW_DEPTH`, raw depth images are *technically* supported. However, they are not supported by PIL. Our current code only looks to see if the mime type is supported by viam, but not if the mime type is supported by PIL. 
This is a hotfix that will temporarily fix this issue. I say temporarily because once [this ticket](https://viam.atlassian.net/browse/RSDK-4089) is approved and merged, it will actually be a moot point.
> [hotfix] Make it such that depth images always return RawImage

- src/viam/app/data/client.py
- tests/mocks/services.py
- tests/test_data_client.py
- tests/test_data_sync_client.py
This PR implements two separate test clients that combine to test every gRPC method wrapper defined in our DataClient class. Tthe PR also implements two mock services that simulate responses from app. One test client/mock service duo is for the data methods, and the other is for the data sync (upload) methods. Finally, the PR also updates binary_data_by_filter() to return a list of bytes--as opposed to a list of SensorData objects.
> [RSDK-3898] Implement Tests for Data Cloud API's

- .github/workflows/docs.yml
This PR removes the kill statements used when generating docs as described by the docs.yml file. Workflows get run in docker that are killed anyway, so we don't need to worry about linger processes.
> Fix Docs Workflow

- src/viam/components/power_sensor/__init__.py
- src/viam/components/power_sensor/client.py
- src/viam/components/power_sensor/power_sensor.py
- src/viam/components/power_sensor/service.py
- tests/mocks/components.py
- tests/test_power_sensor.py
Adds power sensor component and tests. Scope: https://docs.google.com/document/d/1HjShXMyD6HQkZkAo0bvDe61STdxxfyBrVnbRC6nSlM0/edit
> RSDK-4056 Add PowerSensor

- src/viam/app/data_client.py
> Fix typos in upload method docstrings

- src/viam/app/data_client.py
- Tweaking upload method intro description to clarify which tab where (assuming for `file_upload` and `file_upload_from_path` -- please confirm!). Also using `upload X to the app` instead of `sync with` - these commands are uni-directional (i.e. send up, not then-also-bring-down).
- Assuming `remove_tags_from_binary_data_by_filter` should be `untag`, this is an educated guess.
- One more typo
Hope this helps!
> More docstrings clarification

- docs/examples/example.ipynb
- src/viam/app/_logs.py
- src/viam/app/app_client.py
- src/viam/app/data_client.py
- src/viam/app/logs/logs.py
- src/viam/app/viam_client.py
- src/viam/components/power_sensor/client.py
- src/viam/components/power_sensor/service.py
- src/viam/services/slam/client.py
- tests/mocks/services.py
- tests/test_app_client.py
- tests/test_data_client.py
- tests/test_data_sync_client.py
This PR implements and tests all of the remaining APP API's that DON'T return a 'nil pointer dereference' error from our App server. Not included in this PR are the "TODO" comments explaining when/how this error occurs.
> [RSDK-3640] Implement More APP API's

- examples/server/v1/components.py
- src/viam/components/base/base.py
- src/viam/components/base/client.py
- src/viam/components/base/service.py
- tests/mocks/components.py
- tests/test_base.py
Update python SDK to include new base property `wheel_circumference_meters`
Note to reviewers: I am not sure if there's something I have to do to specifically update this PR to use the most recent API changes? I'm seeing some errors which I believe are because it's not referencing the most recent version of API. 
Edit: It passed all the checks though so maybe that was just a local issue
> RSDK-4578: Python SDK Base Properties

- docs/examples/example.ipynb
> Quick fix example ipynb typos

- src/viam/errors.py
To filter captured data, the data management collectors check for a custom [grpc error](https://github.com/viamrobotics/rdk/blob/0a907bf7fdfe4b5649cb0c8598fa41766c542b6f/data/collector.go#L41). Expose this error in the SDK so that users coding in python can return this error in their modular resource code.
> RSDK-4646 Add NoCaptureToStoreError to SDK

- src/viam/components/camera/camera.py
Am I misunderstanding this or are we using sensor as a synonym
> Rename sensor to imager

- src/viam/app/data_client.py
- tests/mocks/services.py
- tests/test_data_client.py
This PR introduces a new input parameter - a boolean specifying whether or not to actually include the binary file data associated with the requested files - to a binary data retrieval method. Before, this variable was simply never passed when the requests were made, and so no actual data was ever actually returned, only metadata. The PR allows for actual data to be retrieved. Also included in the PR is an update to the relevant class's testing suite and some necessary resulting changes to the method taking on this new input parameter.. and also a docstring update.
> [RSDK 4654] Add 'Include Binary' Option

- tests/mocks/services.py
- tests/test_motion_service.py
[RSDK-4544](https://viam.atlassian.net/browse/RSDK-4544)
MoveSingleComponent had already been removed, but there were a couple residual instances of move_single_component in tests, which were removed
[RSDK-4544]: https://viam.atlassian.net/browse/RSDK-4544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-4544: Clean up leftover move_single_component mocks in tests

- examples/server/v1/components.py
- src/viam/components/camera/camera.py
- src/viam/components/camera/client.py
- src/viam/components/camera/service.py
- src/viam/gen/component/camera/v1/camera_pb2.pyi
- tests/mocks/components.py
- tests/test_camera.py
[RSDK-4440](https://viam.atlassian.net/browse/RSDK-4440)
In order to unblock [DATA-1628](https://viam.atlassian.net/browse/DATA-1628)
Adds extra struct to `get_image` and `get_point_cloud` on abstract class method, service, and client.
[RSDK-4440]: https://viam.atlassian.net/browse/RSDK-4440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DATA-1628]: https://viam.atlassian.net/browse/DATA-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-4440: Add extra struct in method signatures for camera

- src/viam/utils.py
Discussed here: https://github.com/viamrobotics/rdk/pull/2839#discussion_r1310713150
> DATA-1813 Add method to get fromDataManagement value from extra map in python SDK

- src/viam/rpc/dial.py
[APP-2517](https://viam.atlassian.net/browse/APP-2517)
Requires changes to rust-utils, [RSDK-4755](https://github.com/viamrobotics/rust-utils/pull/75)
This script (in this case, with the little hacks in place to connect to a robot on localhost):
```python
import asyncio
from viam import logging
from viam.robot.client import RobotClient
from viam.rpc.dial import Credentials, DialOptions
async def connect_robot_location_secret():
creds = Credentials(
type='robot-location-secret',
payload='qymq89tpc8m5fe7o90wf3kxn3tb55eaqj1uchx0ul89puggu')
opts = RobotClient.Options(
refresh_interval=0,
dial_options=DialOptions(credentials=creds)
)
return await RobotClient.at_address('robot-main.gmmaqnzytw.viam.cloud', opts)
async def connect_api_key():
creds = Credentials(
type='api-key', …
```
> APP-2517: org API key support

- docs/examples/example.ipynb
[RSDK-4647](https://viam.atlassian.net/browse/RSDK-4647)
Added note linking to docs for adding to registry
Added sentence clarifying the relationship of the config type, model, name to the component class' type, model, name
[RSDK-4647]: https://viam.atlassian.net/browse/RSDK-4647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-4647: Improve python docs on how to add local module to config

- src/viam/app/viam_client.py
- src/viam/rpc/dial.py
[RSDK-4528](https://viam.atlassian.net/browse/RSDK-4528)
location_id can apparently be none in app_client, so no changes needed there
allowing users to specify app url will make it easier for testing and stuff
[RSDK-4528]: https://viam.atlassian.net/browse/RSDK-4528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-4528 - Allow API keys for cloud apis + allow users to specify app url

- src/viam/robot/client.py
- src/viam/rpc/dial.py
https://viam.atlassian.net/browse/RSDK-3961
> Part of the webhook functionality with ESP32s involves the use of set_power_mode(PowerMode.POWER_MODE_OFFLINE_DEEP). 
> 
> When an ESP32 is in deep sleep, it is essentially off , and will therefore not be able to respond to the SDK. This means the SDK connection will time out on a success, resulting in an error.
> 
> While the user does have control over the sdk client’s retry interval, they don’t have control over how many times a re-connect is attempted. This means that the user can’t determine how long (retry_interval x num_retries) this unnecessary reconnection attempt may live, and therefore can’t control the upper limit on network or compute utilization.
> 
> 
> In dial options, add max_reconnect_attempts
I added the above attribute and …
> RSDK-3961: Add max_reconnect_attempts

- src/viam/robot/client.py
Essentially reverts the guard we removed [here](https://github.com/viamrobotics/viam-python-sdk/pull/418/files#diff-01517e96fd388c85a79f9361c72766cc6227aaf78e617f209f907362968bf65fL286).
> Bugfix: Check connection status before attempting to reconnect

- src/viam/__init__.py
- src/viam/rpc/server.py
- tests/test_server.py
changes key error in cases of missing dependencies to
`KeyError - <viam.proto.common.ResourceName rdk:component:sensor/ at 0x1046165c0> - file_name='examples/simple_module/src/main.py' func_name='new' line_num=26`
from 
`KeyError - namespace: \"rdk\"\ntype: \"component\"\nsubtype: \"camera\"\nname: \"cam\"\n"}`
which should be a bit more info
> RSDK-5145 - better resource name representation, more info in unknown grpc errors

- src/viam/robot/client.py
- src/viam/sessions_client.py
- sessions client was overwriting dial options in the robot client, so making an actual copy
- on reconnect, sessions client actually wants the new socket address, so got that instead of the address of the robot itself
> Fix reconnect logic

- src/viam/components/camera/client.py
https://viam.atlassian.net/browse/RSDK-5174
The first conditional branch of `get_image_from_response` never gets hit because the default `mime_type` value in the invoker— `get_image` in client.py —  is `""` and not `None`.
> RSDK-5174: Fix get_image mimetype handler in python sdk

- src/viam/app/app_client.py
- src/viam/app/data_client.py
- src/viam/app/ml_training_client.py
- src/viam/app/viam_client.py
- src/viam/utils.py
- tests/mocks/services.py
- tests/test_data_client.py
- tests/test_ml_training_client.py
Adds ML Training client.
(Note to reviewers) I am currently running tests to make sure these all work in practice. I expect things to work out and didn't want to delay getting reviewers on it, but it's possible some small fixes will be pushed based on those tests.
> RSDK-4977 - add ml training apis

- examples/server/v1/components.py
- poetry.lock
- src/viam/media/viam_rgba_plugin.py
Pillow [pulled some nonsense](https://github.com/python-pillow/Pillow/pull/7307) by making a breaking change in a minor version. Oops on them. Panic! at the Robot Factory.
> Fix an issue with the new Pillow update

- src/viam/app/data_client.py
- tests/test_data_sync_client.py
Add ability to provide file_extension to binary data capture upload
> [DATA-2034] Add file extensions to binary data capture upload

- src/viam/robot/client.py
- src/viam/rpc/dial.py
Adds a simple helper function for creating connection `Options` for an api-key, with default values elsewhere.
> RSDK-4756 - add `Options` api-key helper function

- src/viam/app/app_client.py
- src/viam/app/billing_client.py
- src/viam/app/data_client.py
- src/viam/app/viam_client.py
- tests/mocks/services.py
- tests/test_billing_client.py
Adds billing client to python SDK.
> RSDK-4907 - Add billing client

- examples/complex_module/src/arm/__init__.py
- examples/complex_module/src/arm/my_arm.py
- examples/complex_module/src/base/__init__.py
- examples/complex_module/src/base/my_base.py
- examples/complex_module/src/gizmo/__init__.py
- examples/complex_module/src/gizmo/my_gizmo.py
- examples/complex_module/src/main.py
- examples/complex_module/src/summation/__init__.py
- examples/complex_module/src/summation/my_summation.py
this way the resource model isn't registered implicitly if some other module imports this library to use the new apis
> RSDK-5501 - Move resource registration out of top level files in example

- docs/examples/example.ipynb
- docs/examples/module_step2.py
- docs/examples/module_step2_optional.py
- docs/examples/module_step3.py
- docs/examples/my_cool_arm.py
- examples/complex_module/src/arm/my_arm.py
- examples/complex_module/src/gizmo/my_gizmo.py
- examples/simple_module/src/main.py
Fix from this [PR](https://github.com/viamrobotics/viam-python-sdk/pull/458).
`close()` calls have to be awaited.
> await example close calls

- src/viam/components/sensor/__init__.py
same thing happened with generic
if there are no messages in that proto file, for some reason the generated file does not include the import at all, even when there are methods in the service
will create a patch release as well
> Fix sensor service not resolving

- docs/examples/example.ipynb
- docs/examples/module_step2.py
- docs/examples/module_step2_optional.py
- docs/examples/module_step3.py
- docs/examples/my_cool_arm.py
- examples/complex_module/src/arm/my_arm.py
- examples/complex_module/src/gizmo/my_gizmo.py
- examples/simple_module/README.md
- examples/simple_module/client.py
- examples/simple_module/src/main.py
updated client as well
as part of testing, found a small issue with our validation code so fixed that as well
also made all the logs info so it'll show up even if not in debug mode
@dannenberg think this is what you wanted
> Fix simple module, update readme

- src/viam/components/camera/service.py
https://viam.atlassian.net/browse/RSDK-5637
> RSDK-5637  Remove mime type inference of PCD within get_image

- src/viam/app/data_client.py
- tests/mocks/services.py
- tests/test_data_sync_client.py
Implements `streaming_data_capture_upload`
> RSDK-4650 - Add streaming data capture upload

- examples/server/v1/components.py
- src/viam/components/board/board.py
- src/viam/components/board/client.py
- tests/mocks/components.py
- tests/test_board.py
This was removed from the RDK in https://github.com/viamrobotics/rdk/pull/3253. From the perspective of the Python SDK, no information is being communicated with this function: it always says that the board is remote and nothing else.
Strictly speaking, this is a breaking change because we don't know who out in the world is using this function. but my understanding is that the entire SDK is still in beta so breaking changes are okay. and anyone using it isn't getting any utility out of it, as previously stated.
> [RSDK-5823] remove Board.model_attributes() from the SDK

- README.md
Add mention of installing with `mlmodel` extra to support the MLModel service. Same copy as [made to Docs site](https://github.com/viamrobotics/docs/pull/2122/files) earlier.
- Some formatting tweaks.
> DOCS-1479: Add mlmodel extra to README

- Makefile
- docs/examples/example.ipynb
- src/viam/components/camera/camera.py
- src/viam/components/camera/client.py
- src/viam/components/camera/service.py
- tests/test_camera.py
Return ViamImage object when using camera component.
Tested using laptop's webcam!
`mycam get_image return value: <viam.media.video.ViamImage object at 0x102f3de10>`
> RSDK-4089: change camera api return types

- src/viam/services/motion/client.py
- tests/mocks/services.py
- tests/test_motion_service.py
[Ticket](https://viam.atlassian.net/browse/RSDK-6011)
New methods are annotated as **Experimental** until the [RPC definition of MoveOnGlobe is changed to be that of MoveOnGlobeNew](https://github.com/viamrobotics/api/pull/411). 
[Follow up PR](https://github.com/viamrobotics/viam-python-sdk/pull/496) will rename `move_on_globe_new` to `move_on_globe` & delete the old `move_on_globe` & remove the **Experimental** annotations.
I'm making these changes now so I can confirm that the [docs ](https://github.com/viamrobotics/docs/pull/2310) update links to the python documentation work as expected.
- Add `move_on_globe_new`, marked as **Experimental** 
- Add `stop_plan`, marked as **Experimental** 
- Add `get_plan`, marked as **Experimental** 
- Add `list_plan_statuses`, marked as …
> RSDK-6011 - Add Motion Expose Paths project RPC methods

- Makefile
- src/viam/components/camera/__init__.py
- src/viam/components/camera/camera.py
- src/viam/components/camera/client.py
- src/viam/components/types.py
- src/viam/media/video.py
- tests/mocks/components.py
- tests/test_camera.py
Prompted by https://github.com/viamrobotics/api/pull/408, we were redefining `Camera.Properties` when we could've simply `TypeAlias`ed it
> TypeAlias Camera.Properties

- examples/server/v1/components.py
- src/viam/components/board/board.py
- src/viam/components/board/client.py
- tests/mocks/components.py
- tests/test_board.py
Within digital interrupts, the `value()` method will get the number of interrupts that have occurred. It's a good thing to have; we'll keep it. However,
- `add_callback()` cannot be implemented without changing the GPRC interface, which will require a scope doc, which will require planning how to do this right. Get rid of it for now: digital interrupts aren't really part of the API yet.
- `add_post_processor()` doesn't exist outside of raspberry pi boards; get rid of it.
- `tick()` is only used in tests (to simulate the interrupt firing). Keep it in `MockDigitalInterrupt`, but get rid of it in the "real" code.
So, how do you use digital interrupts outside of the RDK server? Unfortunately, you kinda can't, and have never been able to. You can repeatedly check its value and do something if …
> [RSDK-5810] remove impossible-to-implement functions from digital interrupts

- src/viam/app/app_client.py
Originally: 
```
Exception: bad argument type for built-in operation
/Users/nicolejung/viam/viam-python-sdk/main.py:20: RuntimeWarning: coroutine 'AppClient._get_organization_id' was never awaited
print(f'Exception: {e}')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Unclosed connection: Channel('app.viam.com', 443, ..., path=None)
```
Now:
```
[api_key {
id: "----"
key: "----"
created_on {
seconds: 1695842752
nanos: 869000000
}
}
authorizations {
authorization_type: "role"
authorization_id: "robot_owner"
resource_type: "robot"
resource_id: "----"
org_id: "----"
}
]
```
> RSDK-5983: await get_org_id in list_keys

- src/viam/components/camera/camera.py
- src/viam/operations.py
- tox.ini
Previously, I wrote the code to assume we were typechecking only on the most recent version of python. That proved short-sighted. 
Fix the issues around type checking pre-py310, and update tox to also typecheck
> Fix tox to include typechecking

- docs/examples/example.ipynb
- src/viam/components/camera/camera.py
- src/viam/components/camera/client.py
- tests/test_camera.py
This will be addressed again in a future API change (see [RSDK-6134](https://viam.atlassian.net/browse/RSDK-6134))
[RSDK-6134]: https://viam.atlassian.net/browse/RSDK-6134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert camera API change for future implementation

- .github/workflows/update_protos.yml
The update protos workflow has been failing because of stale info. The issue is, there is no existing branch for the stale info to be coming from (the branch is auto-deleted once the PR is merged). 
I went ahead and changed the flow to use only git actions that we have more control over, rather than a third-party action.
> Fix update-protos workflow

- src/viam/app/data_client.py
- src/viam/utils.py
- tests/mocks/services.py
- tests/test_data_client.py
- tests/test_dataset.py
[Jira Ticket](https://viam.atlassian.net/browse/RSDK-5731)
Changes:
- Added dataset APIs to /data client (`CreateDataset`, `ListDatasetsByIDs`, `ListDatasetsByOrganizationID`, `RenameDataset`, `DeleteDataset`, `AddBinaryDataToDatasetByIDs`, and `RemoveBinaryDataFromDatasetByIDs`).
- Made a new `Dataset` class in `DataClient` class.
- Made a new `MockDataset` in `mocks/services.py`.
- Created a new `test_dataset.py`.
- Added tests for new DataClient functions.
> RSDK-5731: add dataset apis

- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
Thanks to how pip does its version management, pip install viam-sdk does not work on an arm7l board. This means that for example, any python modules which require the viam SDK are uninstallable.
arm6l is forward compatible to arm7l. An arm7l board can use the arm6l SDK just fine, it just isn't installable by pip without manually downloading and renaming.
This PR repackages the arm6l buld as arm7l.
https://viaminc.slack.com/archives/C039G724TKP/p1709829556782589
> Build arm7l whl

- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
Musl supported in rust-utils as of https://github.com/viamrobotics/rust-utils/pull/102
Unfortunately, github runners does not support aarch64 on Alpine linux in github runners:
https://github.com/actions/runner/issues/1637
https://github.com/actions/runner/issues/801
so this is x64 only for now.
Note that platform compatibility tags are formatted slightly different for musllinux
https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#musllinux
> RSDK-4857 musllinux binaries for python SDK

- src/viam/module/module.py
I'm not seeing any existing tests that simulate the bringing up a python module as a subprocess. I'm not inclined to be the first person to add that test...but I can if it's necessary.
> RSDK-7014: Configure python to flush to stdout despite not being connected to a tty.

- docs/examples/example.ipynb
- src/viam/app/app_client.py
- tests/test_app_client.py
Removes the `_get_organization_id` helper function (which assumed org-level authorization), instead require users to pass org ID to relevant APIs.
Note that, because this is a breaking change, it will be merged into `rc-0.21.0` rather than `main` in order to give users plenty of time to prepare.
> RSDK-5569 - require users to pass org-id

- .github/workflows/publish.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
Actions are only available to members we give permission to (org members and collaborators with appropriate access level). The `is_org_member` check was redundant
> Remove is org member check

- src/viam/robot/client.py
- tests/test_robot.py
~Breaking change!~ Not anymore!
Add `machine_id` to the `get_cloud_metadata` robot client method. ~Also change the return type and rename `robot_part_id` to `machine_part_id` for clarity.~ [We are just deprecating the duplicate field instead](https://github.com/viamrobotics/viam-python-sdk/pull/585#discussion_r1571261813).
Depends on:
> RSDK-7229 add machine_id to cloud metadata

- docs/examples/example.ipynb
- src/viam/app/app_client.py
- src/viam/app/data_client.py
- src/viam/app/ml_training_client.py
- src/viam/components/arm/arm.py
- src/viam/components/board/board.py
- src/viam/components/camera/camera.py
- src/viam/components/encoder/encoder.py
- src/viam/components/motor/motor.py
- src/viam/components/movement_sensor/movement_sensor.py
- src/viam/components/power_sensor/power_sensor.py
- src/viam/resource/base.py
- src/viam/robot/client.py
- src/viam/services/motion/client.py
- src/viam/services/navigation/navigation.py
- src/viam/services/slam/slam.py
- src/viam/services/vision/vision.py
First: This PR changes only code comments (that appear in [Python SDK docs](https://python.viam.dev/)). No code was harmed in the making of this PR!
Fix straightforward correctness issues that are interfering with automated scraping, such as missing params or returns, formatting (mostly indents), etc. Common issues encountered; fixed:
- Params with multiline descriptions must indent wrapped lines, fixed.
- Returns with multiline descriptions must not indent wrapped lines, fixed.
- Converted multi-item returns to single-item returns: they are all really single-item anyways -- 1 tuple -- and the multi-approach resulted in inconsistencies between usage syntax (at function `def`) and parameters (in dedicated Parameters (`Args:`) section).
- Other instances of tuple returns already do this …
> DOCS-2199: Viam Python SDK correctness pass

- .github/workflows/build-wheels.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- .github/workflows/update_protos.yml
Update the build process so that we aren't duplicating a lot of code. This also enables us to build wheels outside of the process of a release, which is useful for the instance where we're manually testing releases (like for `v0.21.0`)
> Build process

- src/viam/components/board/board.py
Just updates the code comment to fix Py SDK docs and downstream consumers (like Docs!). Description pulled from Proto.
Thanks much!
> Add missing param to set_power_mode()

- src/viam/services/mlmodel/client.py
- tests/test_mlmodel.py
As part of the audit of do_command, it came up that we defined `do_command` for an mlmodel client but not service, and that we were doing tests of `do_command` as part of the mlmodel tests. But, `do_command` is not part of the mlmodel protos so we should get rid of it.
> RSDK-7393 - remove references to do_command from mlmodel service

- src/viam/app/data_client.py
- tests/mocks/services.py
- tests/test_data_client.py
Removes the `BinaryData` shadow type, instead returning the raw proto type.
> RSDK-6684 - remove binarydata shadow type

- examples/server/v1/components.py
- examples/server/v1/server.py
- src/viam/components/board/__init__.py
- src/viam/components/board/board.py
- src/viam/components/board/client.py
- src/viam/components/board/service.py
- tests/mocks/components.py
- tests/test_board.py
- `AnalogReader` is now just `Analog`. Similarly, `analog_reader_by_name` is just `analog_by_name`, etc.
- The `Analog` abstract class can now `.write()` in addition to `.read()`.
- (The underlying RPCs are unchanged: it's still a `WriteAnalog` RPC on the board. but SDK users don't interact directly with the RPCs.)
In an upcoming PR, I'll have more board cleanup to stream digital interrupts. but that's separate enough to warrant a separate PR.
> [RSDK-7267] Board cleanup part 1: analogs can be written to

- poetry.lock
- pyproject.toml
- src/viam/media/video.py
- tests/test_media.py
The last remaining bits of PIL in our system were around getting image dimensions. So I implemented new functions around getting dimensions from JPEG, PNG, and Viam RGBA (our 3 supported types). We can now remove PIL entirely (which I did, keeping it as a development dependency only)
> Get Dimensions

- src/viam/components/board/board.py
As I was reading through the newly released `StreamTicks` docs, I noticed the example for Python doesn't show how to consume the stream of "ticks" from the method. I added an `async for` loop to show how a developer could access those values and what fields a "tick" contains.
> fix(components/board): update stream ticks example doc

- src/viam/components/board/__init__.py
- src/viam/components/board/board.py
- src/viam/components/board/client.py
- src/viam/components/board/service.py
- tests/mocks/components.py
- tests/test_board.py
Surprisingly, the compiled protobufs in this repo already have the new data, and all I needed to do was start using it!
When reading an analog pin on a board, you now get the raw value, the minimum/maximum possible value the reader can output, and the minimum change the reader can notice.
> [RSDK-7154] update analog reader interface to include range/accuracy

- src/viam/rpc/dial.py
Removes a small footgun - it's easy to write code like `dial_options=DialOptions({"insecure": True})` and wonder why SSL is still required.
> Force kwargs in DialOptions

- src/viam/robot/client.py
- src/viam/services/vision/__init__.py
- src/viam/services/vision/client.py
- src/viam/services/vision/vision.py
- tests/mocks/services.py
- tests/test_vision_service.py
When `MovementSensor` was still a subclass of `Sensor`, we had to exclude adding registering a `Sensor` subtype with the robot for every `MovementSensor` so as to not duplicate the available resources. 
Now that `MovementSensor` is distinct from `Sensor`, we can remove that check
> [RSDK-4561] Remove unused check

- src/viam/components/camera/service.py
- tests/mocks/components.py
- tests/test_camera.py
Simple PR to add `mime_types` to `GetProperties` response. This field was added to the camera `GetPropertiesResponse ` proto a few months back - see PR [here](https://github.com/viamrobotics/api/pull/408).
> RSDK-7776 - Add mime_types to GetPropertiesResponse

- src/viam/rpc/dial.py
Creates an unverified context to allow for proper connection when dialing to localhost. Additionally, prevents us from improperly setting `server_hostname` to our `api_key_id` when authing with an api-key.
This fix allows us to connect properly to `local.viam.cloud` addresses as well as to `localhost`.
> RSDK-7854 - fix local dialing, server_hostname setting

- docs/examples/example.ipynb
[RSDK-7728](https://viam.atlassian.net/browse/RSDK-7728) Switch to using utils.create_filter in the jupyter example code because the old version was deprecated 
[RSDK-7728]: https://viam.atlassian.net/browse/RSDK-7728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-7728: Update to use non-deprecated create_filter

- src/viam/robot/client.py
- tests/mocks/robot.py
- tests/test_robot.py
[**RSDK-7698**](https://viam.atlassian.net/browse/RSDK-7698): Add Shutdown command to Python SDK
* Implements `RobotClient` `shutdown()` with the same error handling logic as the Go SDK seen in [this PR](https://github.com/viamrobotics/rdk/pull/4042)
* Adds a robot client test by creating a mock robot shutdown service which sends a `ShutdownResponse()` and a mock robot client shutdown which makes a `ShutdownRequest()` and returns the `ShutdownResponse()`
> RSDK-7698: Add Shutdown command to Python SDK

- src/viam/components/arm/arm.py
- src/viam/components/board/board.py
- src/viam/components/camera/camera.py
- src/viam/components/encoder/encoder.py
- src/viam/components/gantry/gantry.py
Questions: 
* Is there any way to manually add a link for a type in the docstrings?
> DOCS-2313: Clean up gantry, camera, board, encoder and arm pages for docs parsing

- src/viam/app/app_client.py
- src/viam/app/data_client.py
- src/viam/services/motion/client.py
* Fix code samples, parameter and return descriptions and formatting
* Update descriptions for more info on grabbing organization and dataset ids 
* Add periods and remove "e.g". bc it causes linting error in docs.viam (we aren't supposed to use it)
Note: Motion move_on_globe and move_on_map configuration object formatting: sub-bulleted list -- still looks slightly odd with indenting but couldn't figure out how to completely fix
> DOCS-2313: Make fixups to app client, data client, and motion service package docs

- src/viam/app/data_client.py
I noticed the [data_client docs](https://docs.viam.com/appendix/apis/data-client/#deletebinarydatabyfilter) were still showing the `Filter` class being imported and constructed directly instead of the recommended `create_filter` utility method. 
This PR updates the docstring for the relevant `*ByFilter` methods to use `create_filter`.
> docs(data_client): update Filter to use create_filter util

- src/viam/robot/client.py
Add code example for `get_cloud_metadata()`, sourced from existing [docs](https://docs.viam.com/appendix/apis/robot/#getcloudmetadata).
> Add get_cloud_metadata code sample

- .github/workflows/test.yml
- add `cache: poetry` param to setup-python action
Faster builds
I did a run [here](https://github.com/viamrobotics/viam-python-sdk/actions/runs/9518864325) and then reran again after it succeeded (to get cache).
Speedup is about 40 seconds for the slowest job (2:30 -> 1:50).
Before and after:
> use poetry cache in CI

- src/viam/media/utils/pil/__init__.py
There was still some lingering confusion as to whether Viam will provide Pillow as a dependency or if the user must. This should hopefully clarify that. 
Cc @mcvella
> Add message to PIL utils

- poetry.lock
- pyproject.toml
- Bump `grpclib` pin
On 0.4.6, graceful_exit hangs pending 2nd SIGTERM, causing a 3.3 second delay when shutting down python modules.
With 0.4.6, RDK fails to stop the process + moves on to the process group:
```log
2024-06-18T14:01:36.096-0400	INFO	robot_server.modmanager.process.local-module-1_/home/awinter/repo/viam-python-sdk/examples/easy_resource/dist/main	pexec/managed_process_unix.go:91	stopping process 433303 with signal terminated
2024-06-18T14:01:39.429-0400	INFO	robot_server.modmanager.process.local-module-1_/home/awinter/repo/viam-python-sdk/examples/easy_resource/dist/main	pexec/managed_process_unix.go:103	stopping entire process group 433303 with signal terminated
2024-06-18T18:01:39.493Z	INFO	robot_server.modmanager	modmanager/manager.go:459	Module successfully closed …
```
> RSDK-7115 bump grpclib to stable 0.4.7

- src/viam/components/arm/arm.py
- src/viam/components/base/base.py
- src/viam/components/board/board.py
- src/viam/components/camera/camera.py
- src/viam/components/encoder/encoder.py
- src/viam/components/gantry/gantry.py
- src/viam/components/generic/generic.py
- src/viam/components/gripper/gripper.py
- src/viam/components/input/input.py
- src/viam/components/motor/motor.py
- src/viam/components/movement_sensor/movement_sensor.py
- src/viam/components/power_sensor/power_sensor.py
- src/viam/components/sensor/sensor.py
- src/viam/components/servo/servo.py
A while ago Eliot asked us to add links back to the main docs from the SDK docs from each method (making it easy to move back and forth). This PR accomplishes that for components. We'll do services and other APIs separate. Open to changes on wording.
> DOCS-2497: Add backlinks to main docs

- src/viam/logging.py
- src/viam/robot/client.py
[Jira Ticket](https://viam.atlassian.net/browse/RSDK-7933)
fixed a bug where formatting logs with arguments did not work.
FLYBY: renamed the `log` method parameter `log` to `message` to keep it consistent with the RDK and the `ModuleHandler`.
> RSDK-7933 fix logging bugs

- src/viam/services/motion/client.py
Separate method description from code sample, merge code sample into one code block. Required for docs to process this sample: all in one code sample. Thank you. This only changes how this method appears in the rendered documentation. Looks good there. No code changes.
> Unify get_pose code sample

- src/viam/app/app_client.py
- tests/mocks/services.py
- tests/test_app_client.py
Context: https://viaminc.slack.com/archives/C02KFSY4H89/p1720458747424109
This addresses the above issue a customer is facing. (In the meantime, Shawn has figured out a workaround) 
With unlisted fragment changes already present in app, we should be making use of `FragmentVisibility` rather than `Public`/`ShowPublic`, and in a future PR, any references to `Public`/`ShowPublic` will be removed entirely.
> [RSDK-8126]: Update fragment methods to use fragment visibility

- .github/workflows/build-wheels.yml
To support Home Assistant's core platforms, x86 (32bit, a.k.a i686/i586/i386) wheels are required. This PR adds that target with the corresponding libviam binary.
> chore: add i686 musllinux wheels

- pyproject.toml
As a [request from Home Assistant maintainers](https://github.com/home-assistant/core/pull/117477#issuecomment-2129331354) and general package etiquette, I've added `homepage`, `repository`, and `documentation` links to the `pyproject.toml` to show up in the details of the PyPi page.
> chore: add homepage, repo, docs urls to pyproject.toml

- poetry.lock
- src/viam/app/viam_client.py
- src/viam/services/service_base.py
- tests/test_viam_client.py
Adds the ability to connect to a machine with an already-connected Viam client
> [RSDK-8045] connect to machine from viam client

- src/viam/media/video.py
Sometimes RDK will append +lazy to the mime type string to specify it as a lazy encoded image. 
Python SDK doesn't require this, as all images are default lazy encoded, and also +lazy will cause an error of 
```
ValueError - 'image/jpeg+lazy' is not a valid CameraMimeType - file_name='enum.py' func_name='__new__' line_num=702
```
Just checking for the +lazy suffix and removing it is enough to solve this issue
> DATA-2827 Removes lazy suffix from input mime type

- Makefile
Ensures that when a user runs `make buf` that they're generating the right API version.
> RSDK-8303-3: use api version in makefile

- src/viam/app/app_client.py
Can leave as is if this was intended but the duplication seems odd to me
> Remove duplication

- src/viam/logging.py
[Jira ticket](https://viam.atlassian.net/browse/RSDK-8341)
If a user doesn't give their thread the time to log (i.e. the user is using a while loop), the logs will never show since the logs are never being awaited. This fix changes logs so that they are being printed in a separate thread, which means that logs aren't dependent on the users.
Tested using both our SDK's `complex_module` as well as @hexbabe 's [module](https://github.com/hexbabe/logs-in-thread-bug-repro).
> RSDK-8341: log on main thread

- .github/workflows/linkcheck.yml
- src/viam/robot/client.py
It seems attaching an s at the end makes it create a link...
> Update linkcheck.yml and fix link

- src/viam/robot/client.py
- tests/test_robot.py
https://viam.atlassian.net/browse/RSDK-7901
> Add MachineStatus to Robot API

- src/viam/components/board/board.py
The current example usage doc comment for the `stream_ticks` method demonstrates using an `async for` loop to process the stream of digital interrupt ticks without awaiting the method call, which is required to fulfill the coroutine and access the `TickStream` response.
> docs(board): stream_ticks method should be awaited to return TickStream iterator

- .github/workflows/license_finder.yml
Based on the available logs, this workflow has been failing for at least 3 months. Before that, the git logs have been removed, so we're not sure when the failure started.
`license_finder` has some issues with Python version 3.12, so now the workflow is using 3.11.5.
In the workflow, the command to run `license_finder` was changed so that errors fail the workflow instead of letting it succeed.
Things I tried that didn't work, wasn't the best solution, or introduced more errors:
- `pip install six` doesn't change anything
- `pip install pip==22.0` introduces another error
- `pip install pip==23.0` introduces another error
- `pip install pip==20.0.2` introduces another error
- `pip install pip==9.0.0` introduces another error
- `curl -sS https://bootstrap.pypa.io/get-pip.py | python3` …
> RSDK-8440: fix license finder

- src/viam/app/data_client.py
- src/viam/services/vision/vision.py
[Data Jira ticket](https://viam.atlassian.net/browse/RSDK-8506)
[Vision Jira ticket](https://viam.atlassian.net/browse/RSDK-8253)
BREAKING CHANGE for anyone using `tabular_data_capture_upload` with positional arguments.
Apparently the function fails without the request times, so presumably there's no one successfully calling it without this argument.
Changes:
- `data_request_times` is no longer optional
- comment changes for `data_request_times` and `component_type`
- comment changes for `get_classifications` and `get_detections`
New docs for `tabular_data_capture_upload`:
> RSDK-8506-RSDK-8253: fix docs

- src/viam/robot/client.py
also adds code sample for shutdown command
> Update machine client to use machine term

- src/viam/components/generic/client.py
- src/viam/services/generic/client.py
We weren't setting the channel on our generic component/service.
> [RSDK-8782] Add channel to generics

- src/viam/components/arm/client.py
- src/viam/components/audio_input/client.py
- src/viam/components/base/client.py
- src/viam/components/board/client.py
- src/viam/components/camera/client.py
- src/viam/components/encoder/client.py
- src/viam/components/gantry/client.py
- src/viam/components/generic/client.py
- src/viam/components/gripper/client.py
- src/viam/components/input/client.py
- src/viam/components/motor/client.py
- src/viam/components/movement_sensor/client.py
- src/viam/components/pose_tracker/client.py
- src/viam/components/power_sensor/client.py
- src/viam/components/sensor/client.py
- src/viam/components/servo/client.py
- src/viam/resource/rpc_client_base.py
- src/viam/resource/types.py
- src/viam/services/generic/client.py
- src/viam/services/mlmodel/client.py
- src/viam/services/motion/client.py
- src/viam/services/navigation/client.py
- src/viam/services/sensors/client.py
- src/viam/services/slam/client.py
- src/viam/services/vision/client.py
- src/viam/utils.py
Adds the gRPC debugging client api.
Note to reviewers: a lot of this is pretty boilerplate. I certainly won't complain if you look at all of it but I think the main places to focus are `rpc_client_base.py` and `utils.py`
Flyby: refactors `dict_to_struct` to make the obj argument type optional, such that we don't need to have `if extra is None: extra = {}` in every method.
Example code:
```python
robot = await connect()
motor = Motor.from_robot(robot, "<my-motor-name>")
md = motor.Metadata()
md.enable_debug_logging('my-cool-key') # the key is optional; if not provided, a random key will be generated
await motor.go_for(rpm=100, revolutions=5, metadata=md)
await robot.close()
```
example logs:
> RSDK-6169 - gRPC debugging client api

- Makefile
- src/viam/app/app_client.py
Request from soleng.
flyby: fix buf generation
> Update some mappings to dicts for ease of updates

- src/viam/resource/easy_resource.py
This allows for users who have a `validate_config` function to continue to use `EasyResource`, and doesn't affect it otherwise. 
Useful for the module generator where we default to `EasyResource`
> Add default validator to easy resource

- pyproject.toml
- src/viam/app/data_client.py
- tests/mocks/services.py
- tests/test_data_client.py
- uv.lock
For context: The return type of the `TabularDataBySQL/MQL` proto has changed to return both a list of structs, the existing return type, and also a list of bytearrays that represent BSON.
- Added a required dependency to `pymongo` to use the `BSON` library
- `BSON` provides a `decode()` function for converting lists of byte sequences into Python dictionaries. 
**Testing**:
- I ensured that date fields are returned as native Python `datetime` objects instead of strings by running tabular_data_by_mql against real tabular data on viam-dev and printed the decoded data and their types: 
- Updated the `TABULAR_QUERY_RESPONSE` testing data to include datetime objects, as the Python SDK will receive date fields in this format.
> RSDK-9146: Change Python TabularDataBySQL/MQL return type to raw BSON

- src/viam/components/board/client.py
- tests/mocks/components.py
- tests/test_board.py
`write_analog` has been removed from the `Board` interface.
> [hotfix] remove write analog

- src/viam/app/data_client.py
We changed the return type of `tabular_data_by_sql/mql` earlier in this PR: https://github.com/viamrobotics/viam-python-sdk/pull/774 but forgot to update the doc string. 
Also, removed the first example here: https://python.viam.dev/autoapi/viam/app/data_client/index.html#viam.app.data_client.DataClient.tabular_data_by_mql since  it is discussed in [this](https://viaminc.slack.com/archives/C0307PGHR7E/p1732030413598659?thread_ts=1732024814.387789&cid=C0307PGHR7E) thread that bson from bson with bson.dumps() does not work, but bson from pymongo with bson.encode() works does work.
> RSDK-9339: Update python doc strings for tabular_data_by_sql/mql

- src/viam/app/data_client.py
We have received feedback that users are unsure of what values to pass in for the GetLatestTabularData parameters, and that having an example in the documentation would help.
The plan is to add similar examples to other SDKs once this PR is approved!
> DATA-3565 Add example parameters to GetLatestTabularData documentation

- src/viam/app/data_client.py
* feedback from bill where he wanted example values in the example 
* tested out example
> DOCS-2347: Update example on GetLatestTabularData

- examples/server/v1/components.py
- src/viam/components/board/board.py
- src/viam/components/board/client.py
- tests/mocks/components.py
- tests/test_board.py
removed:  
- `analog_names()`
- `digital_interrupt_names()`
- test functions of both
> RSDK-9560: remove `AnalogNames` and `DigitalInterruptNames` from python sdk

- src/viam/robot/client.py
Causes the `_check_connection` method to call `sys.exit()` if it reaches the end of the reconnect loop and remains disconnected. Without doing so, it remains alive and attempting to reconnect forever whenever RDK quits non-gracefully, causing a memory leak.
Returning is not sufficient, because the thread still exists and remains managed, so the server's await on process closing never returns. By exiting, the parent module recognizes that its processes have completed and shuts down successfully.
Tested locally by having RDK shutdown with exit code 1 abruptly. With this change, the python module exits once the reconnect loop completes. Without this change, the python module stays alive indefinitely until `kill`ed.
> RSDK-9610 - reconnect loop should exit if it fails

- src/viam/app/data_client.py
> DOCS-3233: Add readings key info to tabular data capture upload

- src/viam/proto/robot/__init__.py
- src/viam/robot/client.py
- tests/mocks/robot.py
- tests/test_robot.py
This PR adds warnings to client calls and Deprecation docstrings to the `discover_components` API in the robot client. To my knowledge, this SDK does not have a server side implementation of this API.
I also pre-emptively removed the tests that call this api - let me know if you'd rather keep those.
I don't usually contribute to the python sdk - so here are my local `uv run make test` warnings and failures - if they matter:
```sh
============================================================== FAILURES ===============================================================
____________________________________________________ test_ndarrays_to_flat_tensors ____________________________________________________
@pytest.mark.filterwarnings("ignore::DeprecationWarning")
def …
```
> [RSDK-9631] Add deprecation warnings to DiscoverComponents

- .github/workflows/linkcheck.yml
Getting lots of duplicate tickets that we don't need. Moving to test once on mondays
> Move link check to be weekly

- src/viam/app/data_client.py
Context here: https://viaminc.slack.com/archives/C0307PGHR7E/p1738787849399009
> Update TabularDataByMQL documentation

- requirements-test.txt
this is the version in `pyproject.toml` and `uv.lock`
> Update requirements-test.txt pillow version to non-CVE version 

- src/viam/app/data_client.py
This PR adds an optional boolean users can specify on the ByMQL method. Typically, all user data is stored in blob storage. Users can now opt in storing their tabular data in a database at a higher cost for faster queries. This boolean allows users to specify which data source they would like.
> DATA-3756 Update TabularDataByMQL to have optional bool for use_recent_data

- src/viam/components/camera/camera.py
* steve wanted a more vanilla example to start, 2 more advanced examples are linked in docs
> DOCS-3284: Add simpler get_image example

- src/viam/robot/client.py
Fix typo, add to description, remove redundant example for stop_all.
Also attempts to fix odd formatting in https://python.viam.dev/autoapi/viam/robot/client/index.html#viam.robot.client.RobotClient.get_models_from_modules but was unable to test due to staging environment changes
> DOCS-3516: Add to get_models_from_modules description

- src/viam/robot/client.py
- src/viam/rpc/dial.py
Add initial connection attempt options such that we can set a number of attempts and a per-attempt timeout.
Note: This works, and we can see it work nicely if we set the timeout _below_ 10 seconds. If the timeout is above 10 seconds, it gets short-circuited by some upstream process that causes us to immediately end after 10 seconds (not even entering the retry loop!). Unclear what's going on here; likely a rust issue and so out of scope for this PR but there's a ticket for it [here](https://viam.atlassian.net/browse/RSDK-10064).
> RSDK-5960 - initial connection options

- pyproject.toml
- src/viam/robot/client.py
- src/viam/rpc/dial.py
- src/viam/sessions_client.py
- tests/test_sessions_client.py
Only send heartbeats for actuating methods.
~I chose to do it this way because (having a list of actuating methods) rather than the opposite (exempting a list of non-actuating methods) because in the API protos, we already have an optional extension called `safety_heartbeat_monitored` on the RPCs. But there's no way to actually grab that value in the client SDKs, so I instead got all the `safety_heartbeat_monitored` from the API protos and listed those out here.~
Now gets actuating option from proto
> [RSDK-9328] Exclude non-actuating methods

- src/viam/services/motion/motion.py
Example switches from arm to gripper incorrectly. Fix to make it all gripper.
> DOCS-3603: Fix get_pose example

- examples/apis.json
- src/viam/components/switch/__init__.py
- src/viam/components/switch/client.py
- src/viam/components/switch/service.py
- src/viam/components/switch/switch.py
- tests/mocks/components.py
- tests/test_switch.py
I was working on a Python module that would benefit from providing a Switch component and ended up implementing it internally to ship it. So this is my follow up work to contribute that implementation to the SDK to match the Go and TypeScript versions.
> feat(components): add switch implementation

- src/viam/app/viam_client.py
- tests/test_viam_client.py
- uv.lock
Blocked on release of https://github.com/viamrobotics/rdk/pull/4853, though tested against those changes locally and was able to create a `ViamClient` successfully.
> RSDK-10208 - create app client from env vars

- .github/workflows/test.yml
- .github/workflows/update_protos.yml
* Creates a parent test to check so we don't have to mark 10 separate tests as required
* Switches to using the `peter-evans` workflow for 
* Provides support for automatic approval and merging of these PRs when all tests pass
Note to reviewers: see inline notes for thoughts/explanations on the code and how it was tested (or why I believe leaving it untested is acceptable)
TODO:
* once this is merged, update the required status checks to only include the umbrella `test`, rather than all the individual ones
> RSDK-10294 & RSDK-9902 - automatically merge proto PRs when tests pass

- src/viam/module/module.py
- src/viam/module/service.py
Tested this by adding a sleep to the example simple module to be over the deadline,  and then changing the sleep on the second go around to be less than the deadline. Without this change, we'd be stuck in a loop of forever trying to add. After, things are handled properly
> [RSDK-8424] Do not add modular resource if deadline has passed

- .github/workflows/build-wheels.yml
Untested (not sure how to test without actually doing a release). logic for why I think this is correct: we're building rust utils on x86_64, the platform name for that is win_amd64 per [docs](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform), which is what we're supposed to use per this [python forum post](https://discuss.python.org/t/wheel-platform-tag-for-windows/9025).
> Fix win platform tag

- src/viam/app/app_client.py
- tests/mocks/services.py
- tests/test_app_client.py
Adds some parity to `get_registry_item` to optionally include markdown documentation for models and modules
> add option to include markdown docs to get_registry_item

- examples/optionaldepsmodule/module.py
- examples/optionaldepsmodule/requirements.txt
- src/viam/module/module.py
This PR imports all built-in resource types on module startup so that modules can build all dependencies without needing to import them themselves
> Add imports

- src/viam/logging.py
@njooma will recognize this: we were trying to help Bijan, and this was a red herring along the way. I'm confident my first commit is useful, less confident in the second one. 
The problem sequence of events is this:
- We create a new `_ModuleHandler` (line 67), which constructs the `_SingletonEventLoopThread` (line 73). 
- Creating that singleton sets `self._loop` to None (old line 36), then spawns a separate thread (line 39) which would properly initialize `self._loop` (old line 42).
- Before the separate thread can run, though, we call `module_handler.emit()` (line 85), which calls `self._worker.get_loop()` (line 94), which throws an exception because the loop isn't initialized yet, because the second thread hasn't had a chance to run yet.
With the changes in the first commit, the loop …
> Fix race condition

- src/viam/app/data_client.py
- tests/test_data_sync_client.py
Context: https://viam.atlassian.net/browse/DATA-4318
We need to add the newly added dataset_ids parameter to the SDKs.
**EDIT:** I'm seeing that tests are failing because it's not looking at the correct API version. Am I supposed to commit the generated proto files?
> DATA-4318: Upping API and Adding Dataset_ids

- src/viam/components/camera/camera.py
- src/viam/components/camera/client.py
- src/viam/components/camera/service.py
- src/viam/components/component_base.py
- src/viam/media/utils/pil/__init__.py
- src/viam/media/video.py
- src/viam/services/vision/client.py
- src/viam/services/vision/service.py
- src/viam/services/worldstatestore/__init__.py
- tests/test_camera.py
- tests/test_media.py
- tests/test_vision_service.py
This PR should supersede https://github.com/viamrobotics/viam-python-sdk/pull/993 and https://github.com/viamrobotics/viam-python-sdk/pull/982
Change the functionality of `CameraMimeType` so that it is not limited only to predetermined values, but has the ability to add `CUSTOM` values of `CameraMimeType` that can be used everywhere in the code. 
`CameraMimeType` continues to behave as a `str` everywhere `str` is accepted, while having additional properties and methods, including `name` and `value` properties, which give it the same properties as the previous `Enum`-type. 
This should prevent the mime-type changes from being a breaking change.
> Update CameraMimeType to allow for custom mimes

- src/viam/sessions_client.py
- tests/test_sessions_client.py
When calling concurrently an API that requires session monitoring a race happens leading to the creation of two sessions. 
Consider two motor if a user calls `GoTo` for each concurrently each resource will create a session. Ultimately the second session created will abort the heartbeat thread spawned by the first session. Leading in turn to the cancellation of the first session by RDK the first motor will then stop.
Interestingly the second motor will be assigned a nil session by RDK which allow the resource to continue to actuate in the absence of heartbeats or a working sessions.
I attempted to fix it by keeping changes as light as possible and avoid reverting [RSDK-4455](https://viam.atlassian.net/browse/RSDK-4455) not a python guru so not sure these changes are sane.
[RSDK-4455]: …
> [RSDK-11569] fix race when creating session
